### ISSUE TITLE
More info about how works the file system

### ISSUE THREAD

**Issue by Zlitus** [zeondev/pluto#28]
Are file persistence? Do we have APIs to connect an "External storage", like a cloud storage? And if yes, where can we store the credentials and stuffs to re-mount it when reloading?

Thank you 👍

**Comment by datkat21** [comment]
Hello! 👋 
The current file system (named the "VirtualFS") uses LocalForage, which uses IndexedDB for storage, so it should be persistent. Regarding your question about cloud or external file storage, we haven't considered that yet, but it may be possible in the future. One solution could be to implement a feature into the virtual file system that allows virtual links to be created and read/write from using function calls. Then, a "helper service" could be the link between the virtual folder in the VFS and the cloud folder on a cloud storage. This can be done using the startup apps feature (in the VirtualFS documentation) to launch a helper app file that would manage the file link. About handling credentials, it'd be up to whoever makes this file link app to handle your credentials storing. (This might be a bit more complicated as the app does not have a backend, and doing some OAuth2 work with services like google drive may not be entirely feasible) Again, this is currently not possible, but could be implemented. Thanks for asking

**Comment by datkat21** [comment]
Closing as this issue is stale and this feature is in development.
