### ISSUE TITLE
VirtualFS not storing files correctly.

### ISSUE THREAD

**Issue by JKincorperated** [zeondev/pluto#34]
VirtualFS reacts badly to files that are not UTF-8 encoded.

Example:

Upload a file containing one byte `0x98`.
Download the file again and view in hex editor.
The file now contains `0xEFBFBD`

**Comment by harshitsuthar77731** [comment]
It appears that VirtualFS encounters issues with non-UTF-8 encoding. As a result, it replaces such files with UTF-8 replacement characters, represented as 0xEF 0xBF 0xBD in hexadecimal. To address this, it's advisable to first convert these files to UTF-8 encoding before uploading them to VirtualFS.

**Comment by datkat21** [comment]
VirtualFS should be used for storing text as it uses JSON strings for file content. Please use UTF-8 as per the JSON string requirements

**Comment by JKincorperated** [comment]
A potential solution could be in the file manager when uploading files, checking if the MIME type is not text other than checking if it is an image, video, etc.

https://github.com/zeondev/pluto/blob/43ac095898592d9a3e71b67d943b9c6905d5ea3a/pkgs/apps/FileManager.js#L167-L171

**Comment by datkat21** [comment]
Binary file upload was only originally intended for uploading those file types, as binary files were never tested

**Comment by JKincorperated** [comment]
I'll give it a test locally.

**Comment by JKincorperated** [comment]
Check #35 for info on changes
