### ISSUE TITLE
Login screen (the one to pick between Zeon and a local account) transition to Desktop extremely laggy

### ISSUE THREAD

**Issue by OwnedByWuigi** [zeondev/pluto#36]
For some reason this only affects Firefox (only tested on 115.11esr) , and, in a way Safari 15. I don't know if this is just Firefox fucking itself up lol

**Comment by datkat21** [comment]
Hi, there shouldn't be any lag when transitioning to the desktop. Could you provide a video of what you are experiencing? It works fine on firefox from my experience. Might also be your hardware.

**Comment by OwnedByWuigi** [comment]
Error in my part - I didn't update Firefox. My bad.

**Comment by datkat21** [comment]
Is the issue resolved on your end?

**Comment by OwnedByWuigi** [comment]
Yes.

**Comment by datkat21** [comment]
OK, it seems that this issue has been resolved. :)
