### ISSUE TITLE
[ Feature request ] Add music players, like yt music or spotify or some

### ISSUE THREAD

**Issue by YUG38** [zeondev/pluto#39]
Make it so either you all have a custom app that we can put link to our playlist on yt music or spotify on and then it will auto import the songs or else just add yt music and spotify itself!

**Comment by mrsofanthiel** [comment]
Pluto is designed to be able to have apps easily developed for it. It woudn't be too hard to create an app that is an i-frame of YouTube music or Spotify, but there may be problems with the i-Frames, as a lot of big websites block them. If you can visit those websites in the web browser they can be added. If you want an app like this, its very easy to make one.

**Comment by ItsLap** [comment]
> Pluto is designed to be able to have apps easily developed for it. It woudn't be too hard to create an app that is an i-frame of YouTube music or Spotify, but there may be problems with the i-Frames, as a lot of big websites block them. If you can visit those websites in the web browser they can be added. If you want an app like this, its very easy to make one.

I agree, this issue has also gone stale so i will close it. If you need something that bad then you should probably just push Ctrl + T because x-frame permissions are very hard to combat without using a proxy. We at pluto are dedicated to keeping this proxy free unlike most web oses.
